# Generated by Django 4.1.4 on 2023-04-29 06:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=260)),
                ('picture', models.ImageField(upload_to='books')),
                ('writer_name', models.CharField(max_length=260)),
                ('regular_price', models.IntegerField()),
                ('discount_price', models.IntegerField(blank=True, default=models.IntegerField(), null=True)),
                ('description', models.TextField()),
                ('is_published', models.BooleanField(default=False)),
                ('crated_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('picture', models.ImageField(upload_to='category_pic')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_image', models.ImageField(null=True, upload_to='course_image')),
                ('course_video', models.CharField(max_length=650, null=True)),
                ('title_1', models.CharField(blank=True, max_length=120, null=True)),
                ('title', models.CharField(max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('description', models.TextField()),
                ('price', models.IntegerField(default=0, null=True)),
                ('discount', models.IntegerField(null=True)),
                ('slug', models.SlugField(blank=True, max_length=500, null=True, unique=True)),
                ('publish_satatus', models.BooleanField(default=False)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category', to='clac.category')),
            ],
        ),
        migrations.CreateModel(
            name='Languege',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('languege_name', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=260)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crs', to='clac.course')),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.IntegerField(null=True)),
                ('thumbnail', models.ImageField(upload_to='video_Thumbnail')),
                ('title', models.CharField(max_length=200)),
                ('youtube_id', models.CharField(max_length=200)),
                ('time_duration', models.IntegerField()),
                ('preview', models.BooleanField(default=False)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cls_video', to='clac.course')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clac.lesson')),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='languege',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clac.languege'),
        ),
    ]
