# Generated by Django 4.1.4 on 2023-04-29 06:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clac', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Whats_learn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pont1', models.CharField(blank=True, max_length=190, null=True)),
                ('pont2', models.CharField(blank=True, max_length=190, null=True)),
                ('pont3', models.CharField(blank=True, max_length=190, null=True)),
                ('pont4', models.CharField(blank=True, max_length=190, null=True)),
                ('pont5', models.CharField(blank=True, max_length=190, null=True)),
                ('pont6', models.CharField(blank=True, max_length=190, null=True)),
                ('pont7', models.CharField(blank=True, max_length=190, null=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clac.course')),
            ],
        ),
    ]
