# Generated by Django 4.1.4 on 2023-04-29 06:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clac', '0002_whats_learn'),
    ]

    operations = [
        migrations.CreateModel(
            name='Requierment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('point_1', models.CharField(blank=True, max_length=260, null=True)),
                ('point_2', models.CharField(blank=True, max_length=260, null=True)),
                ('point_3', models.CharField(blank=True, max_length=260, null=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clac.course')),
            ],
        ),
    ]
