# Generated by Django 4.1.4 on 2023-04-29 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clac', '0003_requierment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='whats_learn',
            name='pont2',
            field=models.CharField(blank=True, default='', max_length=190, null=True),
        ),
    ]
