# Generated by Django 4.1.4 on 2023-04-29 16:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clac', '0004_alter_whats_learn_pont2'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill_Level',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level_name', models.CharField(max_length=120)),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='skill_level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='clac.skill_level'),
        ),
    ]
