# Generated by Django 4.1.4 on 2023-04-29 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clac', '0005_skill_level_course_skill_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='certificate',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='course',
            name='deadline',
            field=models.DateField(blank=True, null=True),
        ),
    ]
